"""
Master script to generate ALL quiz types and combine them into quiz_data.json

Quiz Types:
1. Lecture Quizzes (IDs 1-10) - From Lecture PDFs
2. Video Quizzes (IDs 11-20) - From Video Transcript PDFs  
3. NPTEL Quizzes (IDs 21+) - From Assignment/Solution PDFs
"""

import subprocess
import json
from pathlib import Path

def run_script(script_name, description):
    """Run a Python script and report status."""
    print(f"\n{'=' * 60}")
    print(f"  {description}")
    print(f"{'=' * 60}")
    
    try:
        result = subprocess.run(
            ["python", script_name],
            capture_output=True,
            text=True,
            encoding='utf-8',
            errors='replace'
        )
        
        print(result.stdout)
        
        if result.returncode != 0:
            print(f"❌ Error running {script_name}:")
            print(result.stderr)
            return False
        
        return True
        
    except Exception as e:
        print(f"❌ Failed to run {script_name}: {str(e)}")
        return False


def combine_quizzes():
    """Combine all quiz types into single quiz_data.json."""
    print(f"\n{'=' * 60}")
    print("  COMBINING ALL QUIZZES")
    print(f"{'=' * 60}")
    
    combined = {}
    
    # Load lecture quizzes (IDs 1-10)
    lecture_file = Path("lecture_quizzes.json")
    if lecture_file.exists():
        with open(lecture_file, "r", encoding="utf-8") as f:
            lecture_data = json.load(f)
            combined.update(lecture_data)
            print(f"✅ Loaded {len(lecture_data)} lecture quiz questions")
    else:
        print("⚠️  lecture_quizzes.json not found")
    
    # Load video quizzes (IDs 11-20)
    video_file = Path("video_quizzes.json")
    if video_file.exists():
        with open(video_file, "r", encoding="utf-8") as f:
            video_data = json.load(f)
            combined.update(video_data)
            print(f"✅ Loaded {len(video_data)} video quiz questions")
    else:
        print("⚠️  video_quizzes.json not found")
    
    # Load NPTEL quizzes (IDs 21+)
    nptel_file = Path("ocr_output/extracted_quizzes.json")
    if nptel_file.exists():
        with open(nptel_file, "r", encoding="utf-8") as f:
            nptel_raw = json.load(f)
            
            # Convert NPTEL format to quiz_data format
            nptel_data = {}
            for week_num, week_data in nptel_raw.items():
                for set_name, questions in week_data.items():
                    for idx, q in enumerate(questions, 1):
                        # NPTEL quizzes start from set 21
                        quiz_id = f"{week_num}_{20 + idx}_{idx}"
                        nptel_data[quiz_id] = {
                            "question": q["q"],
                            "options": q["options"],
                            "answer": q["answer"],
                            "explanation": q["explanation"],
                            "clue": q.get("explanation", "")
                        }
            
            combined.update(nptel_data)
            print(f"✅ Loaded {len(nptel_data)} NPTEL quiz questions")
    else:
        print("⚠️  NPTEL quizzes not found")
    
    # Save combined quiz_data.json
    output_file = Path("quiz_data.json")
    with open(output_file, "w", encoding="utf-8") as f:
        json.dump(combined, f, indent=2, ensure_ascii=False)
    
    print(f"\n{'=' * 60}")
    print(f"✅ COMBINED QUIZ DATA SAVED")
    print(f"   Total Questions: {len(combined)}")
    print(f"   Output File: {output_file}")
    print(f"{'=' * 60}")


def main():
    """Generate all quiz types and combine them."""
    print("\n" + "=" * 60)
    print("  QUANTUM STUDY PORTAL - QUIZ GENERATION")
    print("=" * 60)
    print("\nGenerating quizzes from:")
    print("  1. Lecture PDFs → Lecture Quizzes (IDs 1-10)")
    print("  2. Video PDFs → Video Quizzes (IDs 11-20)")
    print("  3. Assignment PDFs → NPTEL Quizzes (IDs 21+)")
    
    # Step 1: Generate Lecture Quizzes
    if not run_script("generate_lecture_quizzes.py", "STEP 1: LECTURE QUIZZES"):
        print("⚠️  Lecture quiz generation had issues, continuing...")
    
    # Step 2: Generate Video Quizzes
    if not run_script("generate_video_quizzes.py", "STEP 2: VIDEO QUIZZES"):
        print("⚠️  Video quiz generation had issues, continuing...")
    
    # Step 3: NPTEL quizzes already exist (parse_quiz_to_json.py)
    print(f"\n{'=' * 60}")
    print("  STEP 3: NPTEL QUIZZES")
    print(f"{'=' * 60}")
    print("✅ NPTEL quizzes already generated by parse_quiz_to_json.py")
    
    # Step 4: Combine all quizzes
    combine_quizzes()
    
    print("\n" + "=" * 60)
    print("  ✅ ALL QUIZ GENERATION COMPLETE!")
    print("=" * 60)


if __name__ == "__main__":
    main()
