
import os

INPUT_FILE = "final_institutions_for_supabase.sql"
OUTPUT_DIR = "sql_batches_v2"
MAX_LINES_PER_FILE = 5500

os.makedirs(OUTPUT_DIR, exist_ok=True)

print(f"Reading {INPUT_FILE}...")
with open(INPUT_FILE, 'r', encoding='utf-8') as f:
    lines = f.readlines()

# Write header as batch 0
# For final_institutions_for_supabase.sql, the header is just the first few lines
# But we need the CREATE TABLE from the original batch_00_setup.sql if we want it complete

header_lines = [
    "-- Merged Institutions Database\n",
    "CREATE TABLE IF NOT EXISTS public.institutions (\n",
    "    id bigint generated by default as identity primary key,\n",
    "    state text not null,\n",
    "    district text,\n",
    "    college_name text not null,\n",
    "    created_at timestamp with time zone default now()\n",
    ");\n\n",
    "ALTER TABLE public.institutions ENABLE ROW LEVEL SECURITY;\n",
    "CREATE POLICY \"Allow public read access\" ON public.institutions FOR SELECT USING (true);\n\n",
    "CREATE INDEX IF NOT EXISTS idx_institutions_state ON public.institutions(state);\n",
    "CREATE INDEX IF NOT EXISTS idx_institutions_district ON public.institutions(district);\n",
    "CREATE INDEX IF NOT EXISTS idx_institutions_name ON public.institutions(college_name);\n\n"
]

with open(os.path.join(OUTPUT_DIR, "batch_00_setup.sql"), 'w', encoding='utf-8') as f:
    f.writelines(header_lines)

print(f"Header written to {OUTPUT_DIR}/batch_00_setup.sql")

# Split the data
insert_lines = [l for l in lines if l.strip().startswith("('") or l.strip().startswith("INSERT INTO")]

batch_num = 1
current_batch = []
current_count = 0

# We need to handle the fact that my FINAL_SQL has INSERT INTO followed by many lines of values
# I'll group them into batches of 5000 records approx

for line in lines:
    if line.strip().startswith("--") or not line.strip():
        continue
    
    current_batch.append(line)
    if "VALUES" in line:
        pass # keep going
    elif ";" in line:
        current_count += 500 # rough estimate of batch size from script
        if current_count >= MAX_LINES_PER_FILE:
            filename = f"batch_{batch_num:02d}_data.sql"
            with open(os.path.join(OUTPUT_DIR, filename), 'w', encoding='utf-8') as f:
                f.writelines(current_batch)
            print(f"  {filename} created.")
            batch_num += 1
            current_batch = []
            current_count = 0

if current_batch:
    filename = f"batch_{batch_num:02d}_data.sql"
    with open(os.path.join(OUTPUT_DIR, filename), 'w', encoding='utf-8') as f:
        f.writelines(current_batch)
    print(f"  {filename} created.")

print("\nSplit complete!")
