-- Merged Institutions Database
CREATE TABLE IF NOT EXISTS public.institutions (
    id bigint generated by default as identity primary key,
    state text not null,
    district text,
    college_name text not null,
    created_at timestamp with time zone default now()
);

ALTER TABLE public.institutions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access" ON public.institutions FOR SELECT USING (true);

CREATE INDEX IF NOT EXISTS idx_institutions_state ON public.institutions(state);
CREATE INDEX IF NOT EXISTS idx_institutions_district ON public.institutions(district);
CREATE INDEX IF NOT EXISTS idx_institutions_name ON public.institutions(college_name);

