INSERT INTO public.institutions (state, district, college_name) VALUES
('Kerala', '', 'Kerala Veterinary & Animal Sciences University'),
('Kerala', '', 'Kerala University of Health Sciences'),
('Madhya Pradesh', '', 'Madhya Pradesh Pashu Chikitsa Vigyan Vishwavidyalaya'),
('Rajasthan', '', 'Maharaja Ganga Singh University'),
('Uttar Pradesh', '', 'Mahamaya Technical University'),
('Uttar Pradesh', 'Lucknow', 'Khwaja Moinuddin Chishti Urdu Arabi-Farsi University'),
('West Bengal', 'Ranchi', 'Sidho-Kanho-Birsha University'),
('Uttarakhand', '', 'Uttarakhand Open University'),
('Haryana', '', 'Maharishi Markandeshwar University'),
('Himachal Pradesh', '', 'Sri Sai University'),
('Madhya Pradesh', '', 'Amity University'),
('Madhya Pradesh', '', 'ITM University'),
('Meghalaya', '', 'Mahatama Gandhi University'),
('Meghalaya', 'East Khasi Hills', 'University of Technology & Management'),
('Punjab', '', 'Sri Guru Granth Sahib World University'),
('Rajasthan', '', 'Raffles University'),
('Rajasthan', 'Jaipur', 'Homoeopathy University'),
('Uttar Pradesh', 'Lucknow', 'Babu Banarasi Das University'),
('Uttar Pradesh', '', 'Shri Venkateshwara University'),
('Telangana', 'Hyderabad', 'Rajiv Gandhi University of Knowledge Technology'),
('Himachal Pradesh', '', 'Indian Institute of Technology'),
('Madhya Pradesh', '', 'Indian Institute of Technology'),
('Rajasthan', 'Jodhpur', 'Indian Institute of Technology'),
('Tamil Nadu', '', 'Indian Institute of Information Technology,Design & Manufacturing(IIITDM)'),
('Sikkim', '', 'National Institute of Technology'),
('Arunachal Pradesh', '', 'National Institute of Technology'),
('Uttarakhand', '', 'National Institute of Technology'),
('Mizoram', '', 'National Institute of Technology'),
('Nagaland', '', 'National Institute of Technology'),
('Meghalaya', '', 'National Institute of Technology'),
('Goa', '', 'National Institute of Technology'),
('Puducherry', '', 'National Institute of Technology'),
('Delhi', 'Delhi', 'National Institute of Technology'),
('Karnataka', 'Mysuru', 'KSGH Music and Performing Arts University'),
('Madhya Pradesh', 'Bhopal', 'Rabindranath Tagore University (formerly known as AISECT University)'),
('Madhya Pradesh', 'Bhopal', 'People''s University'),
('Meghalaya', 'East Khasi Hills', 'William Carey University'),
('Rajasthan', 'Jaipur', 'ICFAI University'),
('Himachal Pradesh', '', 'ICFAI University'),
('Chhattisgarh', 'Raipur', 'ICFAI University'),
('Rajasthan', 'Jaipur', 'Manipal University'),
('Rajasthan', '', 'Sunrise University'),
('Rajasthan', 'Jaipur', 'Mahatma Gandhi University of Medical Sciences & Technology'),
('Uttarakhand', 'Dehradun', 'Graphic Era Hill University'),
('Gujarat', 'Rajkot', 'RK University'),
('Assam', '', 'The Assam Kaziranga University'),
('Chhattisgarh', 'Raipur', 'Kalinga University'),
('Haryana', 'Delhi', 'M.V.N. University'),
('Haryana', '', 'Ansal University'),
('Himachal Pradesh', '', 'Career Point University'),
('Himachal Pradesh', '', 'I.E.C. (India Education Centre) University'),
('Madhya Pradesh', '', 'A.K.S. University'),
('Madhya Pradesh', '', 'Swami Vivekanand University'),
('Rajasthan', 'Jaipur', 'Maharaj Vinayak Global University'),
('Rajasthan', 'Jaipur', 'University of Engineering & Management'),
('Rajasthan', 'Kota', 'Career Point University'),
('Rajasthan', '', 'Sangam University'),
('Rajasthan', 'Delhi', 'NIIT University'),
('Andhra Pradesh', '', 'Dr. Y.S.R. Horticultural Univerity'),
('Assam', 'Kamrup Metropolitan', 'Assam Rajiv Gandhi University of Co-operative Management'),
('Madhya Pradesh', '', 'Rajmata Vijayaraje Scindia Krishi Vishwa Vidyalaya'),
('Maharashtra', '', 'Gondwana University'),
('Andhra Pradesh', '', 'Sri Venkateswara Institute of Medical Sciences'),
('Rajasthan', 'Jaipur', 'J.E.C.R.C University'),
('Arunachal Pradesh', '', 'Indira Gandhi Technological and Medical Science University'),
('Chhattisgarh', '', 'Atal Bihari Bajpayee Vishwavidyalaya'),
('Chhattisgarh', 'Raipur', 'ITM University'),
('Assam', 'Kamrup Metropolitan', 'Assam Science & Technology University'),
('Arunachal Pradesh', '', 'Venkateshwara Open University'),
('West Bengal', 'Kolkata', 'Techno India University'),
('Gujarat', '', 'Children''s University'),
('Uttar Pradesh', 'Delhi', 'The Glocal University'),
('Madhya Pradesh', '', 'Raja Mansingh Tomar Music & Arts University'),
('Rajasthan', '', 'Rajasthan University of Veterinary & Animal Sciences'),
('Bihar', '', 'Bihar Agricultural University'),
('Uttarakhand', 'Dehradun', 'DIT University'),
('Uttarakhand', 'Dehradun', 'IMS Unison University'),
('Punjab', '', 'D.A.V University'),
('Uttarakhand', 'Dehradun', 'Uttaranchal University'),
('Madhya Pradesh', '', 'Techno Global University'),
('Haryana', 'Delhi', 'K.R. Mangalam University'),
('Madhya Pradesh', 'Bhopal', 'Jagran Lakecity University'),
('Haryana', '', 'Shree Guru Gobind Singh Tricentenary University'),
('Haryana', '', 'GD Goenka University'),
('Rajasthan', 'Jodhpur', 'Sardar Patel University of Police Security & Criminal Justice'),
('Haryana', '', 'Jagan Nath University'),
('Uttarakhand', 'Dehradun', 'Swami Rama Himalayan University'),
('Assam', '', 'Kumar Bhaskar Varma Sanskrit & Ancient Studies University'),
('Gujarat', 'Ahmedabad', 'Raksha Shakti University'),
('Gujarat', '', 'Indian Institute of Teacher Education'),
('Karnataka', '', 'Karnataka Folklore University'),
('Karnataka', 'Bengaluru Urban', 'Reva University'),
('Uttar Pradesh', '', 'Shobhit University'),
('Haryana', '', 'SRM University'),
('Arunachal Pradesh', '', 'Himalayan University'),
('Delhi', 'Delhi', 'South Asian Universit y'),
('Chhattisgarh', '', 'Chhattisgarh Kamdhenu Vishwavidyalaya'),
('Assam', 'Kamrup Metropolitan', 'Cotton University'),
('Odisha', '', 'North Orissa University'),
('Uttarakhand', '', 'Sri Dev Suman Uttarakhand Vishwavidyalaya'),
('Karnataka', '', 'Presidency University'),
('Kerala', '', 'Thunchath Ezhuthachan Malayalam University'),
('Rajasthan', '', 'OPJS University'),
('Rajasthan', '', 'Tantia University'),
('Karnataka', 'Bengaluru Urban', 'PES University'),
('Karnataka', 'Bengaluru Urban', 'M.S. Ramaiah University of Applied Sciences'),
('Odisha', 'Khordha', 'Xavier university'),
('Gujarat', 'Ahmedabad', 'C. U. Shah University'),
('Karnataka', '', 'CMR University'),
('Assam', 'Kamrup Metropolitan', 'Srimanta Sankaradeva University of Health Sciences'),
('Tamil Nadu', '', 'Tamilnadu National Law School'),
('Uttarakhand', 'Dehradun', 'Uttarakhand Ayurved University'),
('West Bengal', '', 'Kazi Nazrul University'),
('Haryana', '', 'Indira Gandhi University'),
('Madhya Pradesh', 'Bhopal', 'Sri Satya Sai University of Technology & Medical Sciences'),
('Uttar Pradesh', '', 'Rama University'),
('Rajasthan', 'Jodhpur', 'Maulana Azad University'),
('Tamil Nadu', 'Chennai', 'Tamil Nadu Music and Fine Arts University'),
('Uttarakhand', 'Dehradun', 'Hemwati Nandan Bahuguna Medical Education University'),
('Rajasthan', '', 'Shekhawati University'),
('Haryana', '', 'Al-Falah University'),
('Haryana', '', 'BML Munjal University'),
('Gujarat', '', 'Junagarh Agricultural University'),
('Rajasthan', 'Jaipur', 'Dr. Bhimrao Ambedkar Law University'),
('Uttarakhand', '', 'Veer Chandra Singh Garhwali Uttarakhand University of Horticulture & Forestry'),
('Gujarat', 'Vadodara', 'ITM Vocational University'),
('Karnataka', '', 'Dayananda Sagar University'),
('Sikkim', 'East Sikkim', 'Shri Ramasamy Memorial University Sikkim'),
('Uttar Pradesh', '', 'Madan Mohan Malaviya University of Technology'),
('Maharashtra', 'Mumbai City', 'Amity University'),
('Uttar Pradesh', '', 'Rajiv Gandhi National Aviation University'),
('Arunachal Pradesh', '', 'North East Frontier Technical University'),
('Haryana', '', 'Chaudhary Ranbir Singh University'),
('Chhattisgarh', 'Raipur', 'Amity University'),
('Telangana', 'Hyderabad', 'Nizam''s Institute of Medical Sciences'),
('Arunachal Pradesh', 'Papum Pare', 'Arunodaya University'),
('Karnataka', 'Bengaluru Urban', 'Rai Technology University'),
('Madhya Pradesh', '', 'Maharishi Mahesh Yogi Vedic Vishwavidyalaya'),
('Rajasthan', 'Jaipur', 'IIHMR University'),
('Uttar Pradesh', 'Lucknow', 'Maharishi University of Information Technology'),
('Uttar Pradesh', '', 'Jaypee University'),
('Uttar Pradesh', '', 'U.P. Pandit Deen Dayal Upadhyaya Pashu Chikitsa Vigyan Vishwavidhyalaya Evam Go-Anusandhan Sansthan'),
('Assam', '', 'Assam Women''s University'),
('West Bengal', 'Kolkata', 'Adamas University'),
('West Bengal', 'Kolkata', 'University of Engineering and Management'),
('West Bengal', '', 'JIS University'),
('Punjab', '', 'Sant Baba Bhag Singh University'),
('Chhattisgarh', '', 'O.P. Jindal University'),
('Karnataka', '', 'Institute of Trans-Disciplinary Health Sciences and Technology'),
('Maharashtra', 'Pune', 'Spicer Adventist University'),
('Gujarat', 'Ahmedabad', 'Lakulish Yoga University'),
('Telangana', 'Hyderabad', 'Sri Konda Laxman Telangana State Horticultural University'),
('Bihar', '', 'Mahatma Gandhi Central University'),
('Maharashtra', 'Pune', 'Ajeenkya D.Y. Patil University'),
('Maharashtra', 'Pune', 'Flame University'),
('Gujarat', 'Ahmedabad', 'G.L.S. University'),
('West Bengal', '', 'The Neotia University'),
('Karnataka', 'Surat', 'Srinivas University'),
('Manipur', '', 'Sangai International University'),
('Rajasthan', '', 'R.N.B. Global University'),
('West Bengal', '', 'Diamond Harbour Women''s University'),
('Uttarakhand', '', 'Motherhood University'),
('Gujarat', 'Vadodara', 'GSFC University'),
('Punjab', '', 'Akal University'),
('Uttar Pradesh', '', 'J.S. University'),
('West Bengal', '', 'Bankura University'),
('West Bengal', 'Kolkata', 'West Bengal University of Teachers Training Education Planning and Administration'),
('Madhya Pradesh', 'Bhopal', 'Sanchi University of Buddhist-Indic Studies'),
('Gujarat', '', 'Indian Institute of Public Health'),
('Gujarat', '', 'Institute of Advanced Research'),
('Haryana', '', 'Ch. Bansi Lal University'),
('Punjab', '', 'Maharaja Ranjit Singh Punjab Technical University'),
('Madhya Pradesh', '', 'Maharaja Chhatrasal Bundelkhand Vishwavidyalaya'),
('Delhi', 'Delhi', 'Delhi Pharmaceutical Sciences & Research University'),
('Kerala', 'Thiruvananthapuram', 'A.P.J. Abdul Kalam Technological University'),
('Karnataka', '', 'KLE Technological University'),
('Karnataka', '', 'University of Horticultural Sciences'),
('Gujarat', 'Ahmedabad', 'Institute of Infrastructure Technology Research and Management'),
('Rajasthan', 'Jaipur', 'Maharishi Arvind University Jaipur'),
('Madhya Pradesh', '', 'P.K. University'),
('Punjab', '', 'RIMT University'),
('Maharashtra', 'Mumbai City', 'Maharashtra National Law University'),
('Madhya Pradesh', '', 'Medi-Caps University'),
('Maharashtra', 'Pune', 'MIT Art Design and Technology University'),
('Madhya Pradesh', '', 'Mandsaur University'),
('Madhya Pradesh', '', 'Dr. B. R. Ambedkar University of Social Sciences'),
('Jammu and Kashmir', 'Jammu', 'Central Institute of Buddhist Studies(CIBS)'),
('West Bengal', 'Kolkata', 'Brainware University'),
('Tripura', 'West Tripura', 'Maharaja Bir Bikram University'),
('Haryana', '', 'PDM University'),
('Madhya Pradesh', '', 'Dr. A.P.J Abdul Kalam University'),
('Madhya Pradesh', '', 'Shri Vaishnav Vidyapeeth Vishwavidyalaya'),
('Maharashtra', '', 'Sandip University'),
('Gujarat', '', 'Sankalchand Patel University'),
('Gujarat', 'Bhopal', 'Anant National University'),
('Rajasthan', 'Udaipur', 'Bhupal Nobles University'),
('Gujarat', '', 'Navsari Agriculture University'),
('Jharkhand', 'Ranchi', 'Amity University'),
('Jharkhand', 'Ranchi', 'Pragyan International University'),
('Madhya Pradesh', '', 'Malwanchal University'),
('Jharkhand', '', 'AISECT University'),
('Rajasthan', '', 'Govind Guru Tribal University'),
('Gujarat', 'Rajkot', 'Marwadi University'),
('Odisha', '', 'Khallikote University'),
('Uttar Pradesh', '', 'Siddharth University'),
('West Bengal', 'Kolkata', 'The Sanskrit College and University'),
('Uttar Pradesh', 'Lucknow', 'Era University'),
('Odisha', '', 'Gangadhar Meher University'),
('Uttar Pradesh', '', 'Bennett University'),
('Uttar Pradesh', 'Delhi', 'Sanskriti University'),
('Odisha', 'Khordha', 'Rama Devi Women''s University'),
('Uttar Pradesh', 'Meerut', 'IIMT University'),
('Uttar Pradesh', 'Prayagraj', 'Allahabad State University'),
('Chhattisgarh', '', 'ISBM University'),
('Madhya Pradesh', '', 'G.H Raisoni University'),
('Gujarat', '', 'Plastindia International University'),
('Jharkhand', 'Ranchi', 'Jharkhand Raksha Shakti University'),
('Odisha', 'Khordha', 'International Institute of Information Technology (IIIT)'),
('Jharkhand', 'Ranchi', 'Usha Martin University'),
('Odisha', 'Patna', 'Birla Global University'),
('Assam', 'Kamrup Metropolitan', 'The Assam Royal Global University'),
('Punjab', '', 'CT University'),
('Madhya Pradesh', '', 'Symbiosis University of Applied Sciences (SUAS)'),
('Nagaland', '', 'St. Joseph University'),
('Uttar Pradesh', '', 'Harcourt Butler Technical University'),
('Uttar Pradesh', '', 'Bareilly International University'),
('Rajasthan', 'Udaipur', 'Sai Tirupati University'),
('West Bengal', 'Kolkata', 'St. Xavier''s University'),
('Uttarakhand', '', 'Uttarakhand Aawasiya Viswavidyalaya'),
('Haryana', '', 'Starex University'),
('Madhya Pradesh', '', 'Avantika University'),
('Karnataka', 'Bengaluru Urban', 'Karnataka State Rural Development and Panchayat Raj University'),
('Karnataka', '', 'Garden City University'),
('Maharashtra', '', 'Mody University of Science & Technology'),
('Rajasthan', '', 'Mody University of Science & Technology'),
('Jammu and Kashmir', 'Jammu', 'Cluster University of Jammu'),
('Gujarat', '', 'Karnavati University'),
('Uttar Pradesh', '', 'Banda University of Agriculture & Technology'),
('Gujarat', 'Surat', 'P. P. Savani University'),
('Maharashtra', 'Pune', 'Dr. Vishwanath Karad MIT World Peace University'),
('Uttarakhand', '', 'Himalayan Garhwal University'),
('West Bengal', '', 'Raiganj University'),
('Maharashtra', 'Pune', 'Vishwakarma University'),
('Maharashtra', 'Mumbai City', 'Symbiosis Skills and Open University'),
('Rajasthan', 'Jaipur', 'University of Technology'),
('Punjab', '', 'Sri Guru Ram Das University of Health Sciences'),
('Uttar Pradesh', '', 'Uttar Pradesh University of Medical Sciences'),
('Karnataka', 'Mysuru', 'JSS Science & Technology University'),
('Bihar', '', 'Sandip University'),
('Rajasthan', 'Jaipur', 'Bhartiya Skill Development University'),
('Bihar', '', 'K K University'),
('Manipur', 'Imphal West', 'Manipur Technical University'),
('Uttar Pradesh', '', 'Jananayak Chandrashekhar University'),
('Uttarakhand', 'Dehradun', 'Shri Guru Ram Rai University'),
('Jharkhand', 'Ranchi', 'Sarla Birla University'),
('Karnataka', '', 'Bengaluru North University'),
('Gujarat', '', 'Swarnim Startup & Innovation University'),
('Maharashtra', '', 'Sanjay Ghodawat University'),
('Karnataka', 'Bengaluru Urban', 'Bengaluru Central University'),
('Karnataka', 'Kalaburagi', 'Sharnbasva University'),
('Haryana', '', 'Haryana Vishwakarma Skill University'),
('Uttarakhand', '', 'Bhagwant Global University'),
('Odisha', '', 'Odisha State Open University'),
('Jharkhand', 'Ranchi', 'YBN University'),
('Jharkhand', '', 'Arka Jain University'),
('Manipur', 'Imphal West', 'Manipur University of Culture'),
('Arunachal Pradesh', 'Papum Pare', 'The Global University'),
('Gujarat', '', 'Indrashil University'),
('Kerala', '', 'Chinmaya Vishwavidyapeeth'),
('Gujarat', '', 'Kamdhenu University'),
('Uttarakhand', 'Dehradun', 'Ras Bihari Bose Subharti university'),
('Chhattisgarh', 'Raipur', 'International Institute of Information Technology'),
('Uttarakhand', 'Dehradun', 'Quantum University'),
('Rajasthan', 'Jaipur', 'Rajasthan ILD Skills University (RISU)'),
('Madhya Pradesh', 'Bhopal', 'VIT Bhopal University'),
('Jammu and Kashmir', 'Srinagar', 'Cluster University of Srinagar'),
('Madhya Pradesh', '', 'Pandit S N Shukla University'),
('Telangana', '', 'Kaloji Narayan Rao University of Health Sciences'),
('Madhya Pradesh', '', 'Sage University'),
('Telangana', 'Hyderabad', 'Sri P V Narsimha Rao Telangana Veterinary University'),
('Haryana', '', 'Maharana Partap Horticultural University'),
('Andhra Pradesh', '', 'SRM University'),
('Andhra Pradesh', 'Patna', 'Centurion University of Technology and Management'),
('Haryana', '', 'World University Of Design'),
('Odisha', '', 'Veer Surendra Sai Institute of Medical Science and Research'),
('West Bengal', 'Kolkata', 'Sister Nivedita University'),
('Bihar', 'Patna', 'Amity University'),
('Gujarat', '', 'Sardar Krushinagar Dantiwada Agricultural University'),
('Himachal Pradesh', 'Shimla', 'Himachal Pradesh National Law University'),
('Chhattisgarh', 'Raipur', 'Hemchand Yadav Vishwavidyalaya(Earlier known as Durg Vishwavidyalaya)'),
('Madhya Pradesh', '', 'Renaissance University'),
('Jharkhand', '', 'Binod Bihari Mahto Koylanchal University'),
('Maharashtra', 'Pune', 'D Y Patil International University'),
('Bihar', 'Patna', 'Dr C. V. Raman University'),
('Andhra Pradesh', 'Ranchi', 'Dr Shyama Prasad Mukherjee University'),
('Jharkhand', 'Ranchi', 'Dr. Shyama Prasad University'),
('Gujarat', '', 'Gokul Global University'),
('Gujarat', 'Rajkot', 'Atmiya University'),
('Andhra Pradesh', '', 'VIT-AP University'),
('West Bengal', 'Kolkata', 'Indian Association for the Cultivation of Science (IACS)'),
('Haryana', '', 'IILM University'),
('Madhya Pradesh', 'Bhopal', 'Madhyanchal Professional University'),
('Madhya Pradesh', 'Bhopal', 'Bhabha University'),
('Bihar', '', 'Munger University'),
('Bihar', '', 'Purnea University'),
('Chhattisgarh', 'Raipur', 'Shri Rawatpura Sarkar University'),
('Bihar', '', 'Gopal Narayan Singh University'),
('Madhya Pradesh', '', 'Shri Krishna University'),
('Bihar', 'Patna', 'Patliputra University'),
('Gujarat', 'Vadodara', 'National Rail and Transportation Institute'),
('Madhya Pradesh', '', 'Dharmashastra National Law University'),
('Madhya Pradesh', '', 'Mansarovar Global University'),
('Madhya Pradesh', '', 'Sardar Patel University'),
('Madhya Pradesh', '', 'Dr C V Raman University'),
('Bihar', '', 'Al-Karim University'),
('Chhattisgarh', 'Raipur', 'AAFT University of Media and Arts'),
('Gujarat', '', 'Birsa Munda Tribal University'),
('Jharkhand', '', 'Netaji Subhas University'),
('Karnataka', '', 'Adichunchanagiri University'),
('Maharashtra', 'Mumbai City', 'Chhatrapati Shivaji Maharaj University'),
('Karnataka', '', 'Khaja Bandanawaz University'),
('Manipur', 'Imphal West', 'Dhanamanjuri University'),
('Manipur', '', 'National Sports University'),
('Delhi', 'Delhi', 'Netaji Subhas University of Technology'),
('Jharkhand', '', 'Radha Govind University'),
('Assam', '', 'Krishnaguru Adhyatmik Visvavidyalaya'),
('Jharkhand', 'Patna', 'Capital University'),
('Bihar', 'Patna', 'Bihar Animal Sciences University'),
('Rajasthan', 'Jaipur', 'Apex university'),
('Rajasthan', 'Delhi', 'Lords University'),
('Rajasthan', '', 'Shyam University'),
('Andhra Pradesh', '', 'KREA University'),
('Assam', '', 'Central Institute of Technology(CIT)'),
('Andhra Pradesh', '', 'Saveetha Amaravati University'),
('Sikkim', 'East Sikkim', 'Sikkim State University'),
('Odisha', '', 'AIPH University'),
('Rajasthan', 'Surat', 'Shri Khushal Das University'),
('Odisha', '', 'Gandhi Institute of Engineering & Technology University'),
('Uttarakhand', 'Dehradun', 'Sardar Bhagwan Singh University'),
('Rajasthan', '', 'Bikaner Technical University'),
('Haryana', '', 'Maharishi Balmiki Sanskrit University'),
('Haryana', '', 'Gurugram University'),
('Andhra Pradesh', '', 'Dr. Abdul Haq Urdu University'),
('Manipur', 'Imphal West', 'Manipur International University'),
('Jharkhand', '', 'Ramchandra Chandravansi University'),
('Bihar', '', 'Mata Gujri University'),
('Chandigarh', 'Chandigarh', 'Om Sterling Global University'),
('Gujarat', '', 'Gujarat Maritime University'),
('Andhra Pradesh', '', 'Bharatiya Engineering Science and Technology Innovation University'),
('Jharkhand', 'Ranchi', 'Jharkhand University of Technology'),
('Haryana', '', 'Dr. B.R. Ambedkar National Law University'),
('Jharkhand', 'Ranchi', 'Ram Krishna Dharmath Foundation University'),
('Karnataka', 'Dharwad', 'Shri Dharmasthala Manjunatheshwara University');
