-- ============================================
-- QUANTUM STUDY PORTAL - National College Database
-- Total Records: 43121
-- Source: data.gov.in via GitHub
-- ============================================

-- Step 1: Create Table
CREATE TABLE IF NOT EXISTS public.institutions (
    id bigint generated by default as identity primary key,
    state text not null,
    district text,
    college_name text not null,
    created_at timestamp with time zone default now()
);

-- Step 2: Enable Public Read Access
ALTER TABLE public.institutions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access" ON public.institutions FOR SELECT USING (true);

-- Step 3: Create Index for fast search
CREATE INDEX IF NOT EXISTS idx_institutions_state ON public.institutions(state);
CREATE INDEX IF NOT EXISTS idx_institutions_district ON public.institutions(district);
CREATE INDEX IF NOT EXISTS idx_institutions_name ON public.institutions(college_name);

-- Step 4: Insert All Colleges (batched)

-- Batch 1 (1 to 500)

-- Run this FIRST to create the table and indexes.
